{
    "config": {
        "abort": {
            "already_configured": "Az eszk\u00f6z m\u00e1r konfigur\u00e1lva van",
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Hoszt"
                },
                "data_description": {
                    "host": "A Smarty eszk\u00f6z hosztneve vagy IP-c\u00edme"
                }
            }
        }
    },
    "entity": {
        "binary_sensor": {
            "alarm": {
                "name": "Riaszt\u00e1s"
            },
            "boost_state": {
                "name": "Boost \u00e1llapot"
            },
            "warning": {
                "name": "Figyelmeztet\u00e9s"
            }
        },
        "button": {
            "reset_filters_timer": {
                "name": "Sz\u0171r\u0151k id\u0151z\u00edt\u0151j\u00e9nek vissza\u00e1ll\u00edt\u00e1sa"
            }
        },
        "sensor": {
            "extract_air_temperature": {
                "name": "Kivont leveg\u0151 h\u0151m\u00e9rs\u00e9klete"
            },
            "extract_fan_speed": {
                "name": "Elsz\u00edv\u00f3 ventil\u00e1tor sebess\u00e9g"
            },
            "filter_days_left": {
                "name": "Sz\u0171r\u0151 h\u00e1tral\u00e9v\u0151 napok"
            },
            "outdoor_air_temperature": {
                "name": "K\u00fclt\u00e9ri leveg\u0151 h\u0151m\u00e9rs\u00e9klete"
            },
            "supply_air_temperature": {
                "name": "Bef\u00fajt leveg\u0151 h\u0151m\u00e9rs\u00e9klete"
            },
            "supply_fan_speed": {
                "name": "Bef\u00fav\u00f3 ventil\u00e1tor sebess\u00e9ge"
            }
        },
        "switch": {
            "boost": {
                "name": "Turb\u00f3"
            }
        }
    },
    "issues": {
        "deprecated_yaml_import_issue_auth_error": {
            "description": "A(z) {integration_title} YAML-alap\u00fa konfigur\u00e1ci\u00f3ja megsz\u0171nik, de hiteles\u00edt\u00e9si hiba t\u00f6rt\u00e9nt a megl\u00e9v\u0151 konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sakor. A be\u00e1ll\u00edt\u00e1s nem folytathat\u00f3.\n\nEllen\u0151rizze, hogy a(z) {integration_title} megfelel\u0151en m\u0171k\u00f6dik-e \u00e9s ind\u00edtsa \u00fajra a Home Assistant rendszert a tov\u00e1bbi pr\u00f3b\u00e1lkoz\u00e1shoz.\n\nAlternat\u00edv megold\u00e1sk\u00e9nt elt\u00e1vol\u00edthatja a(z) `{domain}` konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l, ut\u00e1na ind\u00edtsa \u00fajra a Home Assistant rendszert, majd adja hozz\u00e1 manu\u00e1lisan a(z) {integration_title} integr\u00e1ci\u00f3t.",
            "title": "A YAML import\u00e1l\u00e1sa hiteles\u00edt\u00e9si hiba miatt sikertelen"
        },
        "deprecated_yaml_import_issue_cannot_connect": {
            "description": "A(z) {integration_title} YAML haszn\u00e1lat\u00e1val t\u00f6rt\u00e9n\u0151 konfigur\u00e1l\u00e1sa megsz\u0171nik, de a megl\u00e9v\u0151 konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sa sor\u00e1n csatlakoz\u00e1si hiba l\u00e9pett fel.  \nA be\u00e1ll\u00edt\u00e1s nem folytat\u00f3dik.\n\nEllen\u0151rizze, hogy a(z) {integration_title} megfelel\u0151en m\u0171k\u00f6dik-e, majd ind\u00edtsa \u00fajra a Home Assistantot, hogy \u00fajra megk\u00eds\u00e9relje az import\u00e1l\u00e1st.\n\nAlternat\u00edvak\u00e9nt teljesen elt\u00e1vol\u00edthatja a(z) `{domain}` konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l, ind\u00edtsa \u00fajra a Home Assistantot, majd manu\u00e1lisan adja hozz\u00e1 a(z) {integration_title} integr\u00e1ci\u00f3t.",
            "title": "A YAML import\u00e1l\u00e1sa csatlakoz\u00e1si hiba miatt sikertelen"
        },
        "deprecated_yaml_import_issue_unknown": {
            "description": "A(z) {integration_title} YAML-alap\u00fa konfigur\u00e1ci\u00f3ja megsz\u0171nik, de ismeretlen hiba t\u00f6rt\u00e9nt a megl\u00e9v\u0151 konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sakor. A be\u00e1ll\u00edt\u00e1s nem folytathat\u00f3.\n\nEllen\u0151rizze, hogy a(z) {integration_title} megfelel\u0151en m\u0171k\u00f6dik-e \u00e9s ind\u00edtsa \u00fajra a Home Assistant rendszert a tov\u00e1bbi pr\u00f3b\u00e1lkoz\u00e1shoz.\n\nAlternat\u00edv megold\u00e1sk\u00e9nt elt\u00e1vol\u00edthatja a `{domain}` konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l, ut\u00e1na ind\u00edtsa \u00fajra a Home Assistant rendszert, majd adja hozz\u00e1 manu\u00e1lisan a(z) {integration_title} integr\u00e1ci\u00f3t.",
            "title": "A YAML import\u00e1l\u00e1sa ismeretlen hib\u00e1val sikertelen"
        }
    }
}